[mgr]
show_hidden = true

[opener]
edit = [{ run = '$EDITOR "$@"', block = true, for = "unix" }]
open = [{ run = 'zathura "$@"', block = false, for = "unix" }]

[open]
prepend_rules = [{ url = "*.md", use = ["edit"] }]
